api_platform:
    title: 'Voyage nature'
    description : 'Agence de voyages et activités écologiques'
    version : '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
